package com.factotum;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;

/**
 * End-to-end integration tests for the Factotum AI pipeline.
 * Uses WireMock to stub LLM responses and H2 in-memory DB instead of PostgreSQL.
 */
@QuarkusTest
class FactotumE2ETest {

    // E2E-001: Full message ingestion flow - valid message with auth returns 202
    @Test
    void testFullMessageIngestionFlow() {
        given()
            .header("Authorization", "Bearer test-token-secure")
            .contentType(io.restassured.http.ContentType.JSON)
            .body("""
                {
                  "header": {
                    "messageId": "e2ea0001-0000-0000-0000-000000000001",
                    "timestamp": "2026-05-17T10:30:00Z",
                    "sender": "e2e-test-suite",
                    "destination": "factotum_inbound",
                    "contentType": "application/json",
                    "schemaVersion": "1.0"
                  },
                  "body": {
                    "action": "run-diagnostic",
                    "target": "health-check"
                  }
                }
                """)
            .when().post("/api/v1/messages")
            .then()
                .statusCode(202)
                .body("enqueued", is(true))
                .body("messageId", is("e2ea0001-0000-0000-0000-000000000001"))
                .body("queue", is("factotum_inbound"));
    }

    // E2E-002: Health check is accessible without auth (public endpoint)
    @Test
    void testHealthCheckPublicAccess() {
        given()
            .when().get("/api/v1/admin/health")
            .then()
                .statusCode(200)
                .body("status", is("ok"));
    }

    // E2E-003: Authenticated and unauthenticated endpoints behave correctly in same test run
    @Test
    void testAuthBoundaryInSameSession() {
        // Health check - no auth needed
        given()
            .when().get("/api/v1/admin/health")
            .then()
                .statusCode(200);

        // Message ingestion - auth required (valid body so Jackson deserializes, then 401 from missing auth)
        given()
            .contentType(io.restassured.http.ContentType.JSON)
            .body("{\"header\":{\"messageId\":\"00000000-0000-0000-0000-000000000000\",\"timestamp\":\"2026-05-17T00:00:00Z\",\"sender\":\"test-suite\",\"destination\":\"factotum_inbound\",\"contentType\":\"application/json\",\"schemaVersion\":\"1.0\"}, \"body\":{}}")
            .when().post("/api/v1/messages")
            .then()
                .statusCode(401);

        // With correct auth - should succeed
        given()
            .header("Authorization", "Bearer test-token-secure")
            .contentType(io.restassured.http.ContentType.JSON)
            .body("{\"header\":{\"messageId\":\"a58b8882-628b-4a57-b452-f6176c1bb7b3\",\"timestamp\":\"2026-05-17T00:00:00Z\",\"sender\":\"test-suite\",\"destination\":\"factotum_inbound\",\"contentType\":\"application/json\",\"schemaVersion\":\"1.0\"}, \"body\":{\"action\":\"analyze\"}}")
            .when().post("/api/v1/messages")
            .then()
                .statusCode(202);
    }

    // E2E-004: Message with auto-generated UUID when none provided
    @Test
    void testAutoGeneratedMessageId() {
        given()
            .header("Authorization", "Bearer test-token-secure")
            .contentType(io.restassured.http.ContentType.JSON)
            .body("{\"header\":{\"messageId\":null,\"timestamp\":\"2026-05-17T00:00:00Z\",\"sender\":\"test-suite\",\"destination\":\"factotum_inbound\",\"contentType\":\"application/json\",\"schemaVersion\":\"1.0\"}, \"body\":{\"action\":\"analyze\"}}")
            .when().post("/api/v1/messages")
            .then()
                .statusCode(202)
                .body("enqueued", is(true))
                .body("messageId", is(notNullValue()));
    }

    // E2E-005: Multiple messages can be enqueued in sequence
    @Test
    void testMultipleSequentialMessages() {
        for (int i = 1; i <= 3; i++) {
            String msgId = "a" + String.format("%07d", i) + "-0000-0000-0000-000000000000";
            given()
                .header("Authorization", "Bearer test-token-secure")
                .contentType(io.restassured.http.ContentType.JSON)
                .body("{\"header\":{\"messageId\":\"" + msgId + "\",\"timestamp\":\"2026-05-17T00:00:00Z\",\"sender\":\"test-suite\",\"destination\":\"factotum_inbound\",\"contentType\":\"application/json\",\"schemaVersion\":\"1.0\"}, \"body\":{\"action\":\"analyze\",\"index\":" + i + "}}")
                .when().post("/api/v1/messages")
                .then()
                    .statusCode(202)
                    .body("messageId", is(msgId));
        }
    }

    // E2E-006: Different destination queues are preserved correctly
    @Test
    void testDifferentDestinationQueues() {
        String[] queues = {"factotum_inbound", "factotum_tasks", "factotum_events"};

        for (int i = 0; i < queues.length; i++) {
            String msgId = "b" + String.format("%07d", i) + "-0000-0000-0000-000000000000";
            given()
                .header("Authorization", "Bearer test-token-secure")
                .contentType(io.restassured.http.ContentType.JSON)
                .body("{\"header\":{\"messageId\":\"" + msgId + "\",\"timestamp\":\"2026-05-17T00:00:00Z\",\"sender\":\"test-suite\",\"destination\":\"" + queues[i] + "\",\"contentType\":\"application/json\",\"schemaVersion\":\"1.0\"}, \"body\":{\"action\":\"test\"}}")
                .when().post("/api/v1/messages")
                .then()
                    .statusCode(202)
                    .body("queue", is(queues[i]));
        }
    }

    // E2E-007: Complex nested body payload is accepted
    @Test
    void testComplexNestedPayload() {
        given()
            .header("Authorization", "Bearer test-token-secure")
            .contentType(io.restassured.http.ContentType.JSON)
            .body("""
                {
                  "header": {
                    "messageId": "c0000001-0000-0000-0000-000000000000",
                    "timestamp": "2026-05-17T10:30:00Z",
                    "sender": "e2e-complex-sender",
                    "destination": "factotum_inbound",
                    "contentType": "application/json",
                    "schemaVersion": "1.0",
                    "priority": 9,
                    "ttlSeconds": 3600,
                    "context": {"environment": "test", "region": "us-east-1"}
                  },
                  "body": {
                    "action": "multi-step-analysis",
                    "targets": ["src/main/java", "src/test/java"],
                    "config": {"verbose": true, "timeout": 30}
                  }
                }
                """)
            .when().post("/api/v1/messages")
            .then()
                .statusCode(202)
                .body("enqueued", is(true));
    }

    @SuppressWarnings("unchecked")
    private static <T> org.hamcrest.Matcher<T> notNullValue() {
        return (org.hamcrest.Matcher<T>) org.hamcrest.CoreMatchers.notNullValue();
    }
}
